 name: Hello dabbakuti
 on: workflow_dispatch
 jobs:
   hello:
     runs-on: ubuntu-latest 
     steps: 
         - name: Print hello dabbakuti
           run: |
             echo "hello dabbakuti"
             echo "hello srikanth"
