 name: Executing multiple jobs
 on: workflow_dispatch
 jobs:
   build:
     runs-on: ubuntu-latest 
     steps: 
         - name: Print hello build
           run:  echo "this is build job"
   test:
      runs-on: ubuntu-latest
      steps:
        - name: Print hello test
          run: echo "this is test job"

   deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Print hello deploy
          run: echo "this is deploy job"
